#ifndef AL5D_CPP_EVENTS_HPP
#define AL5D_CPP_EVENTS_HPP


namespace al5d
{
    enum EventType
    {
        EVENT_MOVING_FINISHED,
        EVENT_NEW_COMMAND_PLANNED,
        EVENT_EMERGENCY_CLEARED,
        EVENT_HALT_REQUESTED,
        EVENT_CONNECTING_FINISHED,
    };
}


#endif // AL5D_CPP_EVENTS_HPP
