@startuml

namespace al5d_cpp {
    class AL5DBase #eee

    class ConsoleTrait<<AL5DBaseTrait>>
    class LambdaTrait<<AL5DBaseTrait>>
    class SerialTrait<<AL5DBaseTrait>>

    AL5DBase <|-- ConsoleTrait
    AL5DBase <|-- LambdaTrait
    AL5DBase <|-- SerialTrait
}

@enduml
