@startuml

'No activation/deactivation boxes because components are concurent and are continuously running. Also when no call is made.

participant MoveDemo #SkyBlue
participant RobotCommander #LimeGreen-Salmon
participant CommandTransmitter #LimeGreen-Salmon

MoveDemo -> RobotCommander:pose_command_1
MoveDemo -> RobotCommander:degree_command_2
MoveDemo -> RobotCommander:pose_command_3
RobotCommander -> CommandTransmitter:move_command_1
CommandTransmitter ->] :move_command_1
RobotCommander -> CommandTransmitter:move_command_2
CommandTransmitter ->] :move_command_2
RobotCommander -> CommandTransmitter:move_command_3
CommandTransmitter ->] :move_command_3

@enduml
