@startuml

'No activation/deactivation boxes because components are concurent and are continuously running. Also when no call is made.

participant MoveToDegreeDemo #SkyBlue
participant RobotCommander #LimeGreen-Salmon
participant CommandTransmitter #LimeGreen-Salmon

MoveToDegreeDemo -> RobotCommander:pose_command_1
RobotCommander -> CommandTransmitter:move_command_1
CommandTransmitter ->] :move_command_1
MoveToDegreeDemo -> RobotCommander:halt_command
RobotCommander -> CommandTransmitter:stop_command
CommandTransmitter ->] :stop_command
MoveToDegreeDemo -> RobotCommander:pose_command_2
MoveToDegreeDemo -> RobotCommander:unhalt_command
MoveToDegreeDemo -> RobotCommander:pose_command_3
RobotCommander -> CommandTransmitter:move_command_3
CommandTransmitter ->] :move_command_3

@enduml
