@startuml

interface halt_command <<EmptySrv>>
interface degree_command <<DegreeCommandMsg>>
interface unhalt_command <<EmptySrv>>
interface pose_command <<PoseCommandMsg>>
interface stop_command <<EmptySrv>>
interface scheduled_degree_command <<DegreeCommandMsg>>
interface scheduled_pose_command <<PoseCommandMsg>>
interface transmitted_command
interface serialized_command <<StringMsg>>

component CommandScheduler <<ROSNode>> #LimeGreen
component "<u>DemoRunner</u>" <<ROSNode>> as DemoRunner #SkyBlue
component "<u>CommandSerializer</u>" <<ROSNode>> as CommandSerializer #LimeGreen-Salmon
component "<u>CommandTransmitter</u>" <<ROSNode>> as CommandTransmitter #LimeGreen-Salmon

DemoRunner -- halt_command
DemoRunner -- degree_command
DemoRunner -- unhalt_command
DemoRunner -- pose_command
halt_command -- CommandScheduler
unhalt_command -- CommandScheduler
pose_command -- CommandScheduler
degree_command -- CommandScheduler
CommandScheduler -- stop_command
CommandScheduler -- scheduled_degree_command
CommandScheduler -- scheduled_pose_command
CommandTransmitter -- transmitted_command
stop_command -- CommandSerializer
CommandSerializer -- serialized_command
serialized_command -up- CommandTransmitter
scheduled_degree_command -- CommandSerializer
scheduled_pose_command -- CommandSerializer

legend right
  <b><color:SkyBlue>Demo application</color></b>
  <b><color:LimeGreen>High-level interface</color></b>
  <b><color:Salmon>Low-level interface</color></b>
endlegend

@enduml
