@startuml

interface halt_command <<EmptySrv>>
interface degree_command <<DegreeCommandMsg>>
interface unhalt_command <<EmptySrv>>
interface pose_command <<PoseCommandMsg>>
interface command
interface serialized_command <<StringMsg>>

component "<u>DemoRunner</u>" <<ROSNode>> as DemoRunner #SkyBlue
component "<u>CommandSerializer</u>" <<ROSNode>> as CommandSerializer #LimeGreen-Salmon
component "<u>CommandTransmitter</u>" <<ROSNode>> as CommandTransmitter #LimeGreen-Salmon

DemoRunner --( halt_command
DemoRunner --( degree_command
DemoRunner --( unhalt_command
DemoRunner --( pose_command
halt_command -- CommandSerializer
unhalt_command -- CommandSerializer
pose_command -- CommandSerializer
degree_command -- CommandSerializer
CommandTransmitter #--( command
CommandSerializer -- serialized_command
CommandTransmitter --( serialized_command

legend right
  <b><color:SkyBlue>Demo application</color></b>
  <b><color:LimeGreen>High-level interface</color></b>
  <b><color:Salmon>Low-level interface</color></b>
endlegend

@enduml
