@startuml

title Pose command handling

participant MoveToDegreeDemo #SkyBlue
participant CommandSerializer #LimeGreen
participant CommandSerializer #LimeGreen-Salmon
participant CommandTransmitter #LimeGreen-Salmon

    MoveToDegreeDemo -> CommandSerializer:pose_command

    CommandSerializer -> CommandTransmitter:serialized_command
    CommandTransmitter ->]:transmitted_command

@enduml
