@startuml

component "<u>DemoRunner</u>" <<ROSNode>> as DemoRunner #SkyBlue
component "<u>CommandSerializer</u>" <<ROSNode>> as CommandSerializer #LimeGreen-Salmon
component "<u>CommandTransmitter</u>" <<ROSNode>> as CommandTransmitter #LimeGreen

component MoveToPosesDemo #SkyBlue
component MoveAndHaltDemo #SkyBlue
component AL5DSerializer #LimeGreen-Salmon
component SerialTransmitter #LimeGreen-Salmon

note bottom of CommandTransmitter : There could also be no\nCommandTransmitter\nin the system.

DemoRunner <|-- MoveToPosesDemo
DemoRunner <|-- MoveAndHaltDemo
CommandSerializer <|-- AL5DSerializer
CommandTransmitter <|-- SerialTransmitter

legend right
  <b><color:SkyBlue>Demo application</color></b>
  <b><color:LimeGreen>High-level interface</color></b>
  <b><color:Salmon>Low-level interface</color></b>
endlegend

@enduml
