@startuml

'No activation/deactivation boxes because components are concurent and are continuously running. Also when no call is made.

title Multiple commands demo

DemoRunner -> CommandScheduler:pose_command_1
DemoRunner -> CommandScheduler:pose_command_2
CommandScheduler -> CommandSerializer:scheduled_pose_command_1
CommandSerializer -> CommandTransmitter:command_1
CommandScheduler -> CommandSerializer:scheduled_pose_command_2
CommandSerializer -> CommandTransmitter:command_2

@enduml
