@startuml

'No activation/deactivation boxes because components are concurent and are continuously running. Also when no call is made.

title Stop demo

DemoRunner -> CommandScheduler:pose_command_1
CommandScheduler -> CommandSerializer:scheduled_pose_command_1
CommandSerializer -> CommandTransmitter:command_1
DemoRunner -> CommandScheduler:stop_command
DemoRunner -> CommandScheduler:pose_command_2
DemoRunner -> CommandScheduler:continue_command
DemoRunner -> CommandScheduler:pose_command_3
CommandScheduler -> CommandSerializer:scheduled_pose_command_3
CommandSerializer -> CommandTransmitter:command_3

@enduml
