@startuml

state "**Connecting**" as Connecting
Connecting: **do**: check_connecting_progress()

state "**Calibrating**" as Calibrating
Calibrating: **enter**: start_calibrating()
Calibrating: **do**: check_calibrating_progress()

state "**Initializing**" as Initializing
Initializing: **enter**: start_initializing()
Initializing: **do**: check_initializing_progress()


state "**Running**" as Running{
    state "**Idling**" as Idling
    Idling: **do**: schedule_next_command_if_available()

    state "**Moving**" as Moving
    Moving: **enter**: start_next_command()
    Moving: **do**: check_moving_progress()

    [*] -down-> Idling:3
    Idling -right-> Moving:8
    Moving -left-> Idling:9
    Idling -down-> [*]:6
}

state "**Halting**" as Halting

state "**Finalizing**" as Finalizing
Finalizing: **enter**: start_finalizing()
Finalizing: **do**: check_finalizing_progress()

[*] -right-> Connecting
Connecting -down-> Calibrating:1
Calibrating -right-> Initializing:2
Initializing -down-> Running:3
Running -left-> Halting:4
Halting -right-> Running:5
Running -down-> Finalizing:6
Finalizing -right-> [*]:7

@enduml
