@startuml

left to right direction

actor "Robot operator" as robot_operator

rectangle "**System**" <<subsystem>> {
    (1. Move to pose) as move_to_pose
    (2. Move to degree) as move_to_degree
    (3. Halt) as halt
    (4. Unhalt) as unhalt
}

robot_operator -- move_to_degree
robot_operator -- move_to_pose
robot_operator -- unhalt
robot_operator -- halt

@enduml